### PR TITLE
added codecov to travis

### PR DESCRIPTION
**Pull request by davepatterson**

### CODE REVIEW

**Comment by jpotts18** [comment]
I have contributed to one project where they had a rule that if the code coverage ever decreased with a build it wouldn't show a check mark in the list above

**Comment by davepatterson** [comment]
Sounds like a good idea. I have never tried it with codecov, though. I can look into it.

**Comment by davepatterson** [comment]
img_3728

@jpotts18  In codecov settings, we can actually configure to codecov to show when there is a drop off in code coverage percentage wise. The image above is an example of how this works.

**Comment by jpotts18** [comment]
So would the decrease in coverage show up on a pull request? Is this ready to go?

**Pull request merged**
