### PR TITLE
Validatableprotocol

### PR DESCRIPTION
**Pull request by davepatterson**

### CODE REVIEW

**Comment by davepatterson** [comment]
Checking to see where conflicts with #111 are

**Comment by mapo80** [comment]
Hi, I want to know if I can use protocol version of swiftvalidator? Are you going to merge on master?

**Comment by davepatterson** [comment]
@mapo80 I'm going to merge it to the master branch.  I'm just waiting for @dadalar to resolve the conflicts on its PR first.

**Comment by mapo80** [comment]
Ok, thanks for tour answer. For now I'll use branch, later I'll switch to master.

Thanks.

**Pull request closed without merging**
