### PR TITLE
Support frameworks and Carthage package manager

### PR DESCRIPTION
**Pull request by levous**
Hi JPotts, great work!  We're going to give it a go.  I've made project organization changes to support creating a framework from the validation core and rules and the needed changes to support Carthage.  This has no impact on the current project other than to move a few files into specific project folders.  

All the tests still pass!  

I have a test project that uses carthage to embed the result.  https://dl.dropboxusercontent.com/u/142976/SwiftValidatorCarthageTest.zip

thanks

### CODE REVIEW

**Comment by PorterHoskins** [comment]
:+1:

**Comment by jpotts18** [comment]
@levous I have fixed these issues and merged them into the master. Can you validate that it is working correctly?

**Comment by racer1988** [comment]
This refers #56

I guess it is not merged yet 
@levous Would you be able to rebase to complete your PR?

**Comment by jpotts18** [comment]
I am pretty sure carthage is now working in 3.0.2.

**Pull request closed without merging**
