### PR TITLE
Update RegexRule.swift

### PR DESCRIPTION
**Pull request by gromatl**
Set RegexRule to "open class" for allow subclassing in Swift 3

### CODE REVIEW

**Comment by kiwo12345** [comment]
This fixes #162

**Comment by kiwo12345** [comment]
when will this be merged?

**Comment by michalkalis** [comment]
+1 I would like this change to be merged as well, kindly.

**Comment by Jasdev** [comment]
+1, @jpotts18, whenever you get a moment. Thanks for your great work!

**Comment by davepatterson** [comment]
Sorry for the wait guys. I've been busy with other stuff lately. Anyways, cheers!

**Comment by davepatterson** [comment]
Sorry guys. This is now merged into master via #175

**Pull request merged**
