### PR TITLE
Support Swift 3 Xcode Beta 6

### PR DESCRIPTION
**Pull request by ed-mejia**
Solves issue #132

### CODE REVIEW

**Comment by davepatterson** [comment]
I don't have access to my computer right now so I can't parse this but is the Travis CI build failing the result of the tests being written in Swift 1 and 2?

**Comment by ed-mejia** [comment]
It's weird, I'm kind of busy right now to check, **but will do it later today**, additionally I will check if everything works ok in Beta 5.

**Comment by davepatterson** [comment]
For sure! Share what you find!

**Comment by ed-mejia** [comment]
I'm going to need some help here, I'm totally ignorant about Travis CI, but it looks like the build is being done with Xcode 7? 🤔... my last commit fixes everything in the project, it compiles good under Xcode Beta 6, including the test, etc.

**Comment by davepatterson** [comment]
Hey @ed-mejia. Travis CI (continuous integration) is a tool that facilitates the deployment of safer code. It does this by checking your updated code from your app I'll request against the tests that you have previously  written for your code. One obvious benefit of doing this is that your code is always tested against the tests you have in case you forget to manually run all tests yourself.. 

Now onto what may be causing the failure. If you look at the travis.yml file that is in the root of SwiftValidator, you'll notice that it's environment uses the Xcode 7.1 osx image. Swift 3 beta 6 isn't available till Xcode 8. I'm guessing that's why it fails.

**Comment by davepatterson** [comment]
Travis still failing I see. I'm gonna take a look myself shortly.

**Comment by ed-mejia** [comment]
Hey @davepatterson thanks for the info about travis 👍 , I was trying to get it work, but I'm done 😫

If you could check it would be nice 👍

**Comment by kbpontius** [comment]
Great work @ed-mejia & @davepatterson! Any progress on getting this merged so the library can officially support Swift 3?

**Comment by ed-mejia** [comment]
Travis keep faling even in this latest PR https://github.com/jpotts18/SwiftValidator/pull/146

**Comment by davepatterson** [comment]
Yeah, I've been meaning to look into Travis issue but I've been bombarded with work lately. I'll be sure to take another shot sometime this week.

**Comment by Lweek** [comment]
Hi! I would love to request all Rule classes to be opened with `open` accessor. Many of us will need create own project specific Rules. It's not possible override classes or inherit them if they are set as public because Swift 3 limit public scope to module only. @ed-mejia

**Pull request merged**
