### PR TITLE
Single field validation

### PR DESCRIPTION
**Pull request by mathielo**
I found myself in the need of validating single fields at time. This is quite useful when working with responders. 

In my app the user could only move to the next field (by hitting "Next" on the keyboard) once the current field has passed all validation rules.

### CODE REVIEW

**Comment by JohnCoates** [comment]
Excellent job, your added methods works brilliantly

**Comment by lmcd** [comment]
:+1:

**Comment by jpotts18** [comment]
Can you add a test for this?

**Comment by mathielo** [comment]
Hey @jpotts18  sorry for the delay. Finally added the tests! :)

**Pull request merged**
