### PR TITLE
Remote Validation on Validator

### PR DESCRIPTION
**Pull request by davepatterson**
@jpotts18 here's a pull request that adds remote validation to Validator. I have yet to update readme or add tests so this is not ready for merger.

### CODE REVIEW

**Comment by davepatterson** [comment]
I ended up adding another method (remoteValidationRequest) to ValidationDelegate to accomplish this instead of creating a rule that does dynamic validation. I did this to avoid breaking the validation structure that is already in place.

**Comment by jpotts18** [comment]
I am a little concerned that having networking code in this library. It makes me feel like we are trying to accomplish more than just validating UIViews. I also worry that no matter how you try to implement this we are going to end up with a million different issues for people wanting to support JSON, XML, different REST HTTP verbs, etc. 

I originally thought the idea of the DynamicRule would have worked for this and we wouldn't care whether they hit a server with HTTP, local database, or check another UIView. As long as they provide a Closure that responds with a Bool we are fine.

**Comment by davepatterson** [comment]
I agree that networking code should not be a part of the library. But that's why I made a delegate method that puts the networking code in hands of the developer using the library. When a field has remote validation, the remoteValidationRequest method is called with all the information a developer needs to make her server request that will check the field against whatever server-side requirements she has. So I kind of feel like SwiftValidator is not responsible for networking but for only declaring a field to be valid or invalid depending on whether the developer sets remoteValidationRequest's completion handler to true or false.

**Comment by davepatterson** [comment]
But I could just be being too partial.

**Comment by davepatterson** [comment]
@jpotts18 I created branch called remote-validation that has an updated README detailing how remote validation is accomplished. Don't worry, it's my last press on the matter. haha. Just wanted you to see exactly how I went about doing it in effort to remove networking responsibility from SwiftValidator.

**Pull request closed without merging**
