### PR TITLE
Custom messages for regex rules

### PR DESCRIPTION
**Pull request by leodasvacas**
Also using convenience initializers to simplify the code.

### CODE REVIEW

**Comment by glaucocustodio** [comment]
:+1:

**Comment by jpotts18** [comment]
Hey @leodasvacas would the documentation need to be updated to show how to use this feature?

**Comment by leodasvacas** [comment]
@jpotts18 First, thanks for this great tool, me and @glaucocustodio are using it in production and it's been very helpful! We will try to make PRs with the improvements we make. I've updated the README.

**Comment by jpotts18** [comment]
Thank for the updates!

**Pull request merged**
